mysite7/src/blog/urls.py
'''
Created on 2019. 8. 3.

@author: 405-19
'''
from django.urls.conf import path
from blog.views import Main,Detail, Posting, post_delete

#blog/urls.py
app_name='blog'

urlpatterns=[
    #뷰클래스를 url에 등록할 때는 뷰클래스.as_view()로 등록
    path("", Main.as_view(), name='main'),
    #DetailView는 특정모델클래스의 특정 객체를 추출하기 위해 pk라는 매개변수를 사용함
    #127.0.0.1:8000/blog/게시물번호/
    path('<int:pk>/', Detail.as_view(), name='detail'),
    #127.0.0.1:8000/blog/posting/
    path("posting/", Posting.as_view(), name='posting'), 
    path("delete/<int:p_id>/", post_delete, name='delete')
    ]

mysite7/src/mysite7/urls.py
from django.contrib import admin
from django.urls import path, include
#include: 다른 URLConf파일을 등록할 때 사용하는 함수
#path(시작문자열, include(urls.py가 있는 위치))->시작문자열로 요청하는 모든 인터넷주소는 include안에 있는 urls.py가 처리할 수 있도록 등록
#ex) path('test/', include('vote.urls'))->127.0.0.1:8000/test/로 시작하는 모든 요청들을 vote폴더에 urls.py에서 처리할 수 있도록 등록


#등록할 뷰함수를 import
#vote/views.py에 존재하는 test함수 import
from vote.views import test, test_value, test_input, main, detail, vote, result, q_registe, q_update, q_delete, c_registe, c_update, c_delete
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', test),
    path('value/', test_value),
    #127.0.0.1:8000/숫자/로 요청하는 처리는 test_input함수를 호출!
    #호출할 때, 숫자값을 number변수에 인자값으로 사용
    path('<int:number>/', test_input),
    #path함수에 name매개변수: 등록된 뷰의 별칭을 등록하는 매개변수
    #템플릿: {% url 별칭의이름(문자열) %}
    #뷰: reverse 함수로 별칭 기반의 사이트주소 추출가능
    path('vote/', main, name="main"),
    #127.0.0.1/vote/숫자/
    path('vote/<int:q_id>/', detail, name='detail'),
    path('vote/vote/', vote, name='vote'),
    #127.0.0.1:8000/vote/result/Choice객체id숫자/
    path('vote/result/<int:c_id>/', result, name='result'),
    #127.0.0.1:8000/vote/qr/
    path('vote/qr/', q_registe, name='qr'),
    path('vote/qu/<int:q_id>/', q_update, name='qu'),
    path('vote/qd/<int:q_id>/', q_delete, name="qd"),
    path('vote/cr/', c_registe, name='cr'),
    path('vote/cu/<int:c_id>/', c_update, name='cu'),
    path('vote/cd/<int:c_id>/', c_delete, name='cd'),
    #127.0.0.1:8000/cl/로 시작하는 요청들은 customlogin/urls.py에서 처리
    path('cl/', include('customlogin.urls')),
    
    #127.0.0.1:8000/auth/로 시작하는 요청들을 social_django 어플리케이션의 urls.py에서 처리
    #include함수의 namespace 매개변수: 해당 urls.py에 지정된 app_name 값을 사용하지 않고 새로운 그룹명을 지정
    path('auth/', include('social_django.urls', namespace='social')),
    
    #127.0.0.1:8000/blog/로 시작하는 요청들을 blog/urls.py에서 처리
    path('blog/', include('blog.urls')),

]

#setting.py 변수값을 사용할 수 있도록 임포트
from django.conf import settings
#MEDIA_URL과 MEDIA_ROOT를 연결하기 위한 함수 임포트
from django.conf.urls.static import static
#/files/로 시작하는 모든 요청은 파일 업로드/다운로드 처리로 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


mysite7/src/blog/models.py
from django.db import models
#django에서 제공하는 회원 모델 클래스
#1명의 User가 여러개의 글을 작성할 수 있도록 외래키 설정
from django.contrib.auth.models import User

#글 카테고리
class Category(models.Model):
    #카테고리명
    name = models.CharField('카테고리', max_length=10)
    #객체 출력 함수 오버라이딩
    def __str__(self):
        return self.name
#글 내용을 저장
class Post(models.Model):
    #Category 모델클래스 외래키 설정
    #models.PROTECT : Category 객체가 삭제가 될 때, 연결된 Post 객체가 존재하면, 삭제되지 않도록 막아주는 기능
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    #User 모델클래스 외래키 설정
    #models.CASCADE : User 객체가 삭제될 때, 연결된 Post객체들도 같이 삭제되는 기능
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    #제목
    title=models.CharField('제목', max_length=100)
    #글 내용
    #TextField: 글자 수 제한이 없는 문자열 저장공간
    #blank, null: XXXField 생성자의 공통 매개변수
    #blank: form 태그에서 필수로 입력하지 않아도 되는 영역을 설정
    #null: 데이터베이스에 저장할 때 값이 없어도 저장되도록 설정
    content=models.TextField('내용', blank= True, null=True)
    #생성일
    #auto_now_add =True : 객체 생성시 서버의 시간을 자동으로 입력
    pub_date=models.DateField('작성일', auto_now_add=True)
    def __str__(self):
        return self.title
    #Meta 클래스 정의해 정렬순서를 지정
    class Meta:
        #정렬 순서 지정
        #정렬에 사용할 변수들을 리스트 형태로 지정
        #변수이름 앞에 -를 붙이면 내림차순으로 정렬
        ordering = ['-pub_date']

#글에 포함된 이미지
class PostImage(models.Model):
    #어떤 글의 객체인지 연결
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    #이미지파일 저장공간
    #ImageField : 이미지를 저장할 때 사용하는 저장공간
    #upload_to : 클라이언트가 업로드한 파일을 저장 및 접근할 때 서버의 하드디스크 경로
    #%Y: 서버시간 기준의 년
    #%m: 서버시간 기준의 월, %d: 서버 시간 기준의 일
    #클라이언트가 이미지를 업로드하면 images/년/월/일 폴더에 저장함
    image=models.ImageField('이미지', upload_to='image/%Y/%m/%d')

#글에 포함된 파일
class PostFile(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    #클라이언트가 업로드한 파일들은 files/년/월/일 폴더에 저장됨
    file=models.FileField('파일', upload_to='files/%Y/%m/%d')

mysite7/src/blog/forms.py
'''
Created on 2019. 8. 3.

@author: 405-19
'''
from django.forms.models import ModelForm
from blog.models import Post
#from django.forms.fields import ImageField
from django import forms
from django.forms.widgets import ClearableFileInput
class PostingForm(ModelForm):
    #사용자가 업로드할 파일/이미지를 입력받는 공간 생성
    #forms.ImageField : 사용자가 이미지를 선택할 수 있는 입력 공간
    #required: forms.XXField의 공용 매개변수
    #required: 사용자가 꼭 입력하지 않아도 되는 설정을 하는 매개변수
    #ClearableFileInput : <input type='file'>형태의 입력공간에 파일 관련 추가 설정을 할 수 있는 위젯
    #multiple : True->하나의 입력공간에 여러개의 파일을 선택할 수 있도록 허용
    images = forms.ImageField(required=False, widget=ClearableFileInput(attrs={'multiple':True}))
    
    files=forms.FileField(required=False, widget=ClearableFileInput(attrs={'multiple':True}))
    
    class Meta:
        model=Post
        fields=['category', 'title', 'content']

mysite7/src/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from blog.models import Post, PostFile, PostImage
from django.views.generic.edit import FormView
from blog.forms import PostingForm
from django.http.response import HttpResponseRedirect, HttpResponseNotAllowed
from django.urls.base import reverse

#제네릭뷰: 장고에서 제공하는 여러가지 뷰 기능을 구현한 클래스 모음
#ListView: 특정 모델클래스의 객체들을 목록화할 수 있는 기능이 구현된 뷰
#글목록이 뜨는 페이지
class Main(ListView):
    #사용자에게 전달할 HTML파일의 경로
    template_name='blog/main.html'
    #리스트로 뽑은 모델 클래스
    model= Post
    #리스트로 추출한 객체를 HTML에 전달할 때 사용할 이름
    context_object_name='List'
    #한 페이지에 몇 개의 객체가 보여질지 설정
    paginate_by=5
    
#글 상세보기 페이지
#DetailView : 특정 모델클래스의 특정 객체 한개를 추출할 때 사용하는 뷰
class Detail(DetailView):
    #사용자에게 전달할 HTML파일의 경로
    template_name='blog/detail.html'
    #리스트로 뽑은 모델 클래스
    model= Post
    #리스트로 추출한 객체를 HTML에 전달할 때 사용할 이름
    context_object_name='obj'
    #한 페이지에 몇 개의 객체가 보여질지 설정
    paginate_by=5
    
#글 작성 페이지
#XXXMixin: 뷰클래스는 데코레이터를 지정할 수 없기 때문에 login_required와 같은 기능을 뷰에 지정하려면 XXXMixin 클래스를 상속받으면 됨.
#단, 제네릭뷰를 먼저 상속받은 다음에 Mixin클래스를 상속을 받아야 정상적으로 기능이 동작함
#LoginRequiredMixin : login_required 데코레이터와 동일한 기능
from django.contrib.auth.mixins import LoginRequiredMixin
#FormView: 폼 클래스를 바탕으로 사용자에게 입력을 받아 처리하는 뷰
class Posting(LoginRequiredMixin, FormView):
    #사용자에게 전달할 HTML 파일 경로
    template_name='blog/posting.html'
    #연동할 폼 클래스의 이름
    form_class = PostingForm
    #GET 방식으로 요청이 들어오면 등록된 폼클래스의 객체 생성 후 HTML 파일과 함께 전달
    #POST방식으로 요청이 들어오면 사용자의 입력을 바탕으로 폼클래스객체 생성 후 유효한 값인지 (is_valid) 확인한 뒤
    #True값이 반환되면 폼 객체를 저장하는 함수가 호출
    #is_valid() 이후에 호출되는 함수를 오버라이딩해 사용자가 업로드한 이미지나 파일을 바탕으로 PostImage, PostFile객체를 생성
    def form_valid(self, form):
        #Form객체를 Post객체로 변환
        #why?: Post객체를 데이터베이스에 저장할 때 user변수에 값이 들어있지 않은 상태기 때문에 에러가 발생
        #p: 사용자입력을 바탕으로 category, title, content변수가 채워져있는 새로운 Post객체
        p=form.save(commit=False)
        #User정보를 클라이언트의 유저정보로 대입
        #self.request: 해당 뷰를 요청한 클라이언트의 요청정보가 저장된 변수
        #self.request.user: 요청한 클라이언트의 User모델클래스 객체 저장 변수
        p.user=self.request.user
        #데이터베이스에 Post객체 저장
        p.save()
        #사용자가 업로드한 파일 데이터를 바탕으로 PostFile객체 생성
        #사용자가 업로드한 파일의 갯수만큼 반복
        #self.request.FILES: 사용자가 업로드한 파일을 저장한 변수
        #self.request.FILES.getlist(name속성이름): 해당 입력공간에 업로드된 파일 데이터들을 추출
        for f in self.request.FILES.getlist('files'):
            pf=PostFile() #새로운 PostFile객체 생성- 데이터베이스에 저장X
            pf.post = p #새로 만들어진 Post객체와 연동
            pf.file= f #사용자가 업로드한 파일을 FileField에 저장
            pf.save()
        #사용자가 업로드한 이미지데이터를 바탕으로 PostImage객체 생성
        #사용자가 'images' 입력공간에 업로드한 파일들을 바탕으로 객체생성
        for i in self.request.FILES.getlist('images'):
            #새로운 PostImage객체 생성 - 데이터베이스에 저장 X
            pi=PostImage()
            pi.post=p
            pi.image = i
            pi.save()
        #blog:detail로 리다이렉트
        #새로 만들어진 Post객체의 id 값으로 detail뷰의 주소 전달
        return HttpResponseRedirect(reverse('blog:detail', args=(p.id,)))
    
#글 삭제 기능
def post_delete(request, p_id):
    #post객체 한개 추출
    p=get_object_or_404(Post, id=p_id)
    #추출한 객체의 user정보와 요청한 클라이언트의 user정보를 비교
    if p.user==request.user:
        #자기가 쓴 글을 지우는 요청인 경우, 추출한 객체를 삭제
        p.delete()
        #메인 페이지로 이동
        return HttpResponseRedirect(reverse('blog:main'))
    else:
        #자기가 쓴 글이 아닌데 요청을 한 경우, 404Error 전달
        return HttpResponseNotAllowed()

mysite7/src/blog/templates/blog/detail.html
{%extends 'base.html'%}

{%block content%}
{#obj : Post 객체 한개#}
<h3>[ {{obj.category}} ] {{obj.title}}</h3>
<h3>작성자 : {{ obj.user }}</h3>
<h4> {{obj.pub_date}} </h4>
<!--  pre: 해당 태그 안에 작성된 내용은 여러 개의 공백, 엔터가 화면에 그대로 출력되는 태그 -->
<pre>{{ obj.content }}</pre>
<!-- 첨부파일 다운로드 링크 -->
<!-- obj.postfile_set.all: obj라는 Post객체와 연결된 모든 PostFile 객체 추출하는 함수 -->
{% for pf in obj.postfile_set.all %}
<!-- 파일필드변수.url : 해당 파일을 접근하기 위한 url주소를 저장한 변수 -->
    <a download href="{{pf.file.url}}">첨부파일</a>
    <br>
{% endfor %}
<!-- 이미지파일을 출력 -->
{% for pi in obj.postimage_set.all %}
<!-- img태그 : HTML화면에 이미지를 출력할 때 사용하는 태그
src속성에 띄울 이미지의 경로(하드디스크 경로나 인터넷 경로)를 지정해야함 -->
    <img src="{{pi.image.url}}" width="40%">
    <br>
{%endfor%}

<!-- 작성자에 한해 삭제버튼 제공 -->
<!-- obj.user : view에서 넘겨받은 post객체가 저장한 user값 -->
{% if %}
    <a href="{% url 'blog:delete' obj.id %}">삭제</a>
{% endif %}

<a href="{% url 'blog:main%}">메인으로 돌아가기</a>
{%endblock%}

mysite7/src/blog/templates/blog/main.html
{#main.html#}
{%extends 'base.html' %}

{%block content%}
<!-- 이전 페이지 버튼, 다음 페이지 버튼 -->
<!-- ListView 클래스가 HTML파일에게 페이지정보를 접근할 수 있는 변수인 page_obj 변수를 내부적으로 전달함 -->
{%if page_obg.has_previous%}
<!-- ListView는 사용자가 몇 번째 페이지를 요청했는지 page변수값으로 확인
이전페이지나 다음페이지로 이동할 링크를 만들 때도 page변수에 값을 대입
page_obj.has_previous, has_next: 이전페이지, 다음페이지의 존재 여부 확인 함수
page_obj.previous_page_number, next_page_number: 현재 클라이언트가 요청한 페이지를 기준으로 이전페이지와 다음페이지 값이 저장된 변수 -->
    <a href="?page={{page_obj.previous_page_number}}">이전페이지</a>
{%else%}
    <a>이전페이지</a>
{%endif%}

{%if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">다음페이지</a>
{%else%}
    <a>다음페이지</a>
{%endif%}

<!-- 글 목록 -->
<table width="100%">
    <tr>
       <th> 글번호 </th>
       <th> 카테고리 </th>
       <th> 글제목 </th>
       <th> 작성자 </th>
       <th> 생성일 </th>
    </tr>
    {#view가 넘겨준 list변수에 요소를 하나씩 추출해 출력#}
    {% for post in list %}
        
        <tr>
            <th>{{ post.id }}</th>
            <th>{{ post.category }}</th>
            <th>
               <a href="{%url 'blog:detail'%}">
                   {{ post.title }}
               </a>
            </th>
            <th>{{ post.user }}</th>
            <th>{{ post.pub_date }}</th>
        </tr>
    {% endfor %}
</table>

<!-- 글쓰기 링크 -->
<a href="{% url 'blog:posting' %}">글쓰기</a>

{%endblock%}

mysite7/src/blog/templates/blog/posting.html
{% extends 'base.html' %}

{% block content %}
{# form: 제네릭뷰가 넘겨준 폼 객체 #}
{# form.as_p, as_ul, as_table 함수로 HTML코드 변환 및 출력 #}

<h3>글 작성 페이지</h3>
<!-- 웹 클라이언트가 서버에게 파일 정보를 업로드하려면 form태그의 enctype속성에 "multipart/form-data"값을 저장해야함 -->

<form action='' method='post' enctype="multipart/form-data">
        {% csrf_token %}
        
        <table width=50%>
            {{ form.as_table }}
        </table>
        <input type="submit" value="갱신">

</form>
{% endblock %}